export default [
  {
    id: 1,
    image: "/games/single.png",
    gameName: "Single",
    type: "open",
    type2: "close",
  },
  {
    id: 2,
    image: "/games/jodi.gif",
    gameName: "Jodi",
    type: "open",
  },
  {
    id: 3,
    image: "/games/dp.gif",
    gameName: "SP Pana",
    type: "open",
    type2: "close",
  },
  {
    id: 5,
    image: "/games/dp.gif",
    gameName: "DP Pana",
    type: "open",
    type2: "close",
  },
  {
    id: 6,
    image: "/games/dp.gif",
    gameName: "TP Pana",
    type: "open",
    type2: "close",
  },
  {
    id: 7,
    image: "/games/half-sangam.gif",
    gameName: "Half-Sangam",
    type: "open",
  },
  {
    id: 8,
    image: "/games/half-sangam.svg",
    gameName: "Full Sangam",
    type: "open",
  },
  {
    id: 9,
    image: "/games/sp.gif",
    gameName: "SP",
    type: "open",
    type2: "close",
  },
  {
    id: 10,
    image: "/games/sp.gif",
    gameName: "DP",
    type: "open",
    type2: "close",
  },
  {
    id: 11,
    image: "/games/jodi-family.gif",
    gameName: "Jodi Family",
    type: "open",
  },
  {
    id: 12,
    image: "/games/red-jodi.gif",
    gameName: "Red Jodi",
    type: "open",
  },
  {
    id: 13,
    image: "/games/red-family-jodi.gif",
    gameName: "Red Jodi Family",
    type: "open",
  },
  {
    id: 14,
    image: "/games/cycle-pana.gif",
    gameName: "Cycle Pana",
    type: "open",
    type2: "close",
  },
  {
    id: 15,
    image: "/games/family-pana.gif",
    gameName: "Family Pana",
    type: "open",
    type2: "close",
  },
];
