export default [
  {
    id: 2,
    name: "Shiv Nights",
    game_status: "running",
    open_result: 123,
    open_result_sum: 6,
    open_time: "22:12",
    close_result: null,
    close_result_sum: null,
    close_time: "23:12",
    order_id: 1,
    monday: "on",
    tuesday: "on",
    wednesday: "on",
    thursday: "on",
    friday: "off",
    saturday: "off",
    sunday: "on",
    today: "on",
    created_at: "2023-03-05T15:53:09.385221+05:30",
    mobile: 1,
  },
  {
    id: 3,
    name: "test",
    game_status: "running",
    open_result: null,
    open_result_sum: null,
    open_time: "17:25",
    close_result: null,
    close_result_sum: null,
    close_time: "21:25",
    order_id: 1,
    monday: "on",
    tuesday: "on",
    wednesday: "off",
    thursday: "off",
    friday: "off",
    saturday: "off",
    sunday: "off",
    today: "on",
    created_at: "2023-03-20T15:25:51.572300+05:30",
    mobile: 1,
  },
  {
    id: 1,
    name: "Raja Rani Morning",
    game_status: "time_out",
    open_result: 777,
    open_result_sum: 1,
    open_time: "03:17",
    close_result: null,
    close_result_sum: null,
    close_time: "02:17",
    order_id: 5,
    monday: "on",
    tuesday: "on",
    wednesday: "on",
    thursday: "off",
    friday: "on",
    saturday: "on",
    sunday: "on",
    today: "on",
    created_at: "2023-02-28T00:17:13.432625+05:30",
    mobile: 1,
  },
];
